# -*- coding: utf-8 -*-
"""KODE PROGRAM PROJECT CEK MB DYELOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsZhI4zdeL9jPfB6ocEU5YwOW5vlT-gr
"""

import io
import re
import pandas as pd
import streamlit as st

# Konfigurasi Halaman Streamlit
st.set_page_config(
    page_title="MB-VANGUARD | Audit Data Manufacture Basic",
    page_icon="⚡",
    layout="wide",
)

# Custom Styling CSS
st.markdown(
    """
    <style>
    .stApp {
        background-color: #F0F8FF;
        color: #111111;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .main-header {
        background: linear-gradient(135deg, #00B4DB 0%, #0083B0 100%);
        padding: 20px;
        border-radius: 12px;
        color: white;
        text-align: center;
        box-shadow: 0 4px 15px rgba(0, 180, 219, 0.3);
        margin-bottom: 20px;
    }
    .main-header h1 {
        margin: 0;
        font-size: 2rem;
        font-weight: 700;
    }
    .main-header p {
        margin: 5px 0 0 0;
        font-size: 1rem;
        opacity: 0.9;
    }
    div[data-testid="metric-container"] {
        background-color: #FFFFFF;
        border: 2px solid #E1E8ED;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    div[data-testid="metric-container"] label {
        color: #111111 !important;
        font-weight: 700 !important;
    }
    div[data-testid="metric-container"] [data-testid="stMetricValue"] {
        color: #0083B0 !important;
        font-weight: 700 !important;
    }
    div.stButton > button {
        background-color: #FFD700;
        color: #111111;
        font-weight: 700;
        border: none;
        border-radius: 8px;
        padding: 10px 24px;
        box-shadow: 0 4px 10px rgba(255, 215, 0, 0.4);
        transition: all 0.3s ease;
    }
    div.stButton > button:hover {
        background-color: #FFC700;
        transform: translateY(-2px);
        box-shadow: 0 6px 15px rgba(255, 215, 0, 0.6);
    }
    section[data-testid="stSidebar"] {
        background-color: #E6F2FF;
        border-right: 1px solid #CCE4FF;
    }
    section[data-testid="stSidebar"] span,
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] label,
    section[data-testid="stSidebar"] div {
        color: #111111 !important;
        font-weight: 600;
    }
    </style>
""",
    unsafe_allow_html=True,
)

# Header Tampilan Web
st.markdown(
    """
    <div class="main-header">
        <h1>⚡ MB-VANGUARD</h1>
        <p>Manufacture Basic - Intelligent Data Validation & Unified Audit System</p>
    </div>
""",
    unsafe_allow_html=True,
)

# --- SIDEBAR NAVIGASI ---
st.sidebar.markdown("### 🧭 Menu Navigasi MB-VANGUARD")
menu_pilihan = st.sidebar.radio(
    "Pilih Menu:", ["📂 Master Data (Upload)", "🚀 Proses & Analisis Data"]
)

# Inisialisasi Session State
if "processed_df" not in st.session_state:
  st.session_state.processed_df = None
if "raw_master" not in st.session_state:
  st.session_state.raw_master = None
if "raw_dyelot" not in st.session_state:
  st.session_state.raw_dyelot = None
if "benang_incorrect_kodes" not in st.session_state:
  st.session_state.benang_incorrect_kodes = set()

# --- MENU 1: MASTER DATA (UPLOAD) ---
if menu_pilihan == "📂 Master Data (Upload)":
  st.markdown("### 📂 Unggah File Master Export ERP & Master Dyelot")
  st.write(
      "Silakan upload file master export Excel gudang serta file Master"
      " Dyelot (Resep) pada bagian di bawah ini."
  )

  st.markdown("#### 1. File Master Export Gudang (MB)")
  uploaded_files = st.file_uploader(
      "Pilih file Excel master gudang (.xlsx)",
      type=["xlsx"],
      accept_multiple_files=True,
      key="upload_mb",
  )

  st.markdown("#### 2. File Master Dyelot / Resep Obat")
  uploaded_dyelot_files = st.file_uploader(
      "Pilih file Excel Master Dyelot / Resep (.xlsx)",
      type=["xlsx"],
      accept_multiple_files=True,
      key="upload_dyelot",
  )

  if uploaded_files:
    all_dataframes = []
    for file in uploaded_files:
      try:
        df_raw = pd.read_excel(file, header=None)
        if len(df_raw) > 8:
          df_trimmed = df_raw.iloc[4:-4].copy()
        else:
          df_trimmed = df_raw.copy()

        header_row_idx = None
        for idx, row in df_trimmed.iterrows():
          row_str = str(row.values)
          if (
              "Tanggal" in row_str
              and "Gudang" in row_str
              and "Kode" in row_str
          ):
            header_row_idx = idx
            break

        if header_row_idx is not None:
          df_trimmed.columns = df_trimmed.loc[header_row_idx]
          df_clean = df_trimmed.loc[header_row_idx + 1 :].copy()
        else:
          df_clean = df_trimmed.iloc[1:].copy()
          df_clean.columns = df_trimmed.iloc[0].values

        df_clean = df_clean.dropna(how="all")
        all_dataframes.append(df_clean)
      except Exception as e:
        st.error(f"Gagal memproses file MB {file.name}: {e}")

    if all_dataframes:
      master_raw_combined = pd.concat(all_dataframes, ignore_index=True)
      st.session_state.raw_master = master_raw_combined
      st.success("✅ File Master Gudang (MB) berhasil di-upload dan dibersihkan!")

  if uploaded_dyelot_files:
    all_dyelot_dfs = []
    for file in uploaded_dyelot_files:
      try:
        df_dyelot_raw = pd.read_excel(file)
        all_dyelot_dfs.append(df_dyelot_raw)
      except Exception as e:
        st.error(f"Gagal memproses file Dyelot {file.name}: {e}")

    if all_dyelot_dfs:
      dyelot_combined = pd.concat(all_dyelot_dfs, ignore_index=True)
      st.session_state.raw_dyelot = dyelot_combined
      st.success("✅ File Master Dyelot (Resep) berhasil di-upload!")

  if (
      st.session_state.raw_master is not None
      or st.session_state.raw_dyelot is not None
  ):
    st.markdown("---")
    st.markdown("#### Preview Data Master Gudang (MB):")
    if st.session_state.raw_master is not None:
      st.dataframe(st.session_state.raw_master.head(10), use_container_width=True)
    else:
      st.info("Belum ada file Master Gudang yang di-upload.")

    if st.session_state.raw_dyelot is not None:
      st.markdown("#### Preview Data Master Dyelot (Resep):")
      st.dataframe(
          st.session_state.raw_dyelot.head(10), use_container_width=True
      )

# --- MENU 2: PROSES & ANALISIS DATA ---
elif menu_pilihan == "🚀 Proses & Analisis Data":
  st.markdown("### 🚀 Eksekusi Sistem Validasi & Audit MB + Resep Dyelot")

  if st.session_state.raw_master is None:
    st.warning(
        "⚠️ Belum ada data Master Gudang yang di-upload. Silakan lakukan upload"
        " di menu **Master Data (Upload)** terlebih dahulu!"
    )
  else:
    if st.session_state.raw_dyelot is None:
      st.info(
          "ℹ️ Informasi: File Master Dyelot belum di-upload. Audit resep obat"
          " khusus TBB dengan PIBC tidak akan berjalan, namun pengecekan"
          " kuantitas standar tetap berjalan."
      )

    if st.button("🚀 Jalankan Proses & Validasi Data Lengkap"):
      with st.spinner(
          "Sedang mengeksekusi validasi ganda (cek benang & cek obat ke"
          " Crosscheck Qty)..."
      ):
        master_df = st.session_state.raw_master.copy()

        # Bersihkan nama kolom dari spasi ekstra
        master_df.columns = [
            str(c).strip() if pd.notna(c) else f"Unnamed_{i}"
            for i, c in enumerate(master_df.columns)
        ]

        # Pemetaan Kolom Fleksibel (Keyword Matching) Master MB
        col_mapping_std = {}
        for c in master_df.columns:
          col_mapping_std[str(c).strip().upper()] = c

        col_kode_item = None
        col_nama_item = None
        col_target_qty = None
        col_target_unit = None
        col_qty = None
        col_unit = None

        for k, v in col_mapping_std.items():
          if "KODE" in k and ("ITEM" in k or "BARANG" in k):
            col_kode_item = v
          elif ("NAMA" in k or "DESKRIPSI" in k or "URAIAN" in k) and (
              "ITEM" in k or "BARANG" in k
          ):
            col_nama_item = v
          elif "TARGET" in k and "QTY" in k:
            col_target_qty = v
          elif "TARGET" in k and "UNIT" in k:
            col_target_unit = v
          elif k in ["QTY", "JUMLAH", "QUANTITY"]:
            col_qty = v
          elif k in ["UNIT", "SATUAN"]:
            col_unit = v

        if not col_kode_item:
          for k, v in col_mapping_std.items():
            if "KODE" in k:
              col_kode_item = v
              break
        if not col_nama_item:
          for k, v in col_mapping_std.items():
            if "NAMA" in k or "BARANG" in k:
              if v != col_kode_item:
                col_nama_item = v
                break
        if not col_target_qty:
          for k, v in col_mapping_std.items():
            if "TARGET" in k:
              col_target_qty = v
              break
        if not col_target_unit:
          for k, v in col_mapping_std.items():
            if "UNIT" in k and v != col_unit:
              col_target_unit = v
              break
        if not col_qty:
          for k, v in col_mapping_std.items():
            if "QTY" in k:
              col_qty = v
              break
        if not col_unit:
          for k, v in col_mapping_std.items():
            if "UNIT" in k and v != col_target_unit:
              col_unit = v
              break

        # Pastikan kolom Keterangan dan Keterangan Lain ada di dataframe
        for c_name in ["Keterangan", "Keterangan Lain"]:
          if c_name not in master_df.columns:
            master_df[c_name] = ""

        # 1. Forward Fill untuk kolom utama per Kode Transaksi
        target_ffill_cols = [
            "Gudang",
            "Kode",
            "Kode Barang Jadi",
            "Nama Barang Jadi",
            "Keterangan",
            "Keterangan Lain",
        ]
        for col in target_ffill_cols:
          if col in master_df.columns:
            if "Kode" in master_df.columns and col != "Kode":
              master_df[col] = master_df.groupby("Kode")[col].ffill()
            master_df[col] = master_df[col].ffill()

        # Fungsi konversi angka aman
        def parse_numeric(val):
          if pd.isna(val) or str(val).strip() == "":
            return None
          if isinstance(val, (int, float)):
            return float(val)
          try:
            s = str(val).strip()
            if "," in s and "." in s:
              if s.find(",") > s.find("."):
                s = s.replace(".", "").replace(",", ".")
              else:
                s = s.replace(",", "")
            elif "," in s and "." not in s:
              s = s.replace(",", ".")
            return float(s)
          except:
            return pd.to_numeric(str(val), errors="coerce")

        # 2. QTY Target Standar (GR)
        if col_target_qty and col_target_unit:
          master_df["QTY Target Standar (GR)"] = master_df.apply(
              lambda row: (
                  parse_numeric(row[col_target_qty]) * 1000
                  if str(row.get(col_target_unit, ""))
                  .strip()
                  .upper()
                  in ["KG", "KGS"]
                  else parse_numeric(row[col_target_qty])
              )
              if parse_numeric(row.get(col_target_qty)) is not None
              else "",
              axis=1,
          )
          cols = list(master_df.columns)
          if (
              "QTY Target Standar (GR)" in cols
              and col_target_unit in cols
          ):
            cols
